#!/bin/bash
docker buildx create --name multiarch --use
docker buildx build --load --platform linux/arm64,linux/amd64 . -t 2martens/qodana-jvm-community-drone-plugin:2023.2 -t 2martens/qodana-jvm-community-drone-plugin:latest
