#!/bin/bash
docker buildx create --name multiarch --use
docker buildx build --load --platform linux/amd64 . -t 2martens/qodana-jvm-community-drone-plugin:2023.2-amd64
docker buildx build --load --platform linux/arm64 . -t 2martens/qodana-jvm-community-drone-plugin:2023.2-arm64
docker manifest create 2martens/qodana-jvm-community-drone-plugin:2023.2 2martens/qodana-jvm-community-drone-plugin:2023.2-amd64 2martens/qodana-jvm-community-drone-plugin:2023.2-arm64
docker tag 2martens/qodana-jvm-community-drone-plugin:2023.2 2martens/qodana-jvm-community-drone-plugin:latest
