#!/bin/bash
docker buildx create --name multiarch --use
docker buildx build --push --platform linux/amd64,linux/arm64 . -t 2martens/qodana-jvm-community-drone-plugin:2023.2 -t 2martens/qodana-jvm-community-drone-plugin:latest
